-- SELECT * FROM EMPRESAS

-- SELECT * FROM FUNCIONARIOS

-- SELECT * FROM EMPRESA_FUNCIONARIO

SELECT F.NOME, E.NOME 
FROM EMPRESA_FUNCIONARIO EF 
	INNER JOIN EMPRESAS E ON (E.ID = EF.ID_EMPRESA)
	INNER JOIN FUNCIONARIOS F ON (F.ID = EF.ID_FUNCIONARIO)
WHERE E.NOME = 'BRy Tecnologia S.A.'