-- DROP TABLE EMPRESA_FUNCIONARIO;
-- DROP TABLE EMPRESAS;
-- DROP TABLE FUNCIONARIOS;

CREATE TABLE COMPANIES(
	ID SERIAL PRIMARY KEY,
	CNPJ VARCHAR(14) NOT NULL UNIQUE,
	NAME VARCHAR(100) NOT NULL,
	LOCATION VARCHAR(100) NOT NULL
);

CREATE TABLE EMPLOYEES(
	ID SERIAL PRIMARY KEY,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	NAME VARCHAR(100) NOT NULL,
	LOCATION VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(20) NOT NULL UNIQUE,
	PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE COMPANY_EMPLOYEE(
	ID SERIAL PRIMARY KEY,
	COMPANY_ID INTEGER REFERENCES COMPANIES(ID),
	EMPLOYEE_ID INTEGER REFERENCES EMPLOYEES(ID)
);
